# Generated by Django 4.1.5 on 2023-12-15 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeBean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(help_text='원두 원산지', max_length=15)),
                ('bean_name', models.CharField(help_text='원두 이름', max_length=50, unique=True)),
                ('region', models.CharField(help_text='지역 이름', max_length=50, null=True)),
                ('grade', models.CharField(help_text='원두 등급', max_length=10)),
                ('processiong_method', models.CharField(help_text='원두 가공 방법', max_length=10, null=True)),
                ('stock', models.PositiveBigIntegerField(help_text='원두 재고')),
                ('date_receipt', models.DateTimeField(help_text='입고 날짜')),
                ('price', models.PositiveIntegerField(help_text='원두 가격')),
                ('aroma', models.PositiveSmallIntegerField(help_text='향미')),
                ('flavor', models.PositiveSmallIntegerField(help_text='맛')),
                ('acidity', models.PositiveSmallIntegerField(help_text='산미')),
                ('texture', models.PositiveSmallIntegerField(help_text='질감')),
                ('aftertastes', models.PositiveSmallIntegerField(help_text='후미')),
                ('uniformity', models.PositiveSmallIntegerField(help_text='일관성')),
                ('balance', models.PositiveSmallIntegerField(help_text='균형감')),
                ('cleancup', models.PositiveSmallIntegerField(help_text='깔끔함')),
                ('sweetness', models.PositiveSmallIntegerField(help_text='단맛')),
                ('total_score', models.PositiveSmallIntegerField(help_text='종합 점수')),
            ],
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('is_hot', models.BooleanField()),
                ('price', models.PositiveIntegerField(help_text='커피 가격')),
                ('size', models.CharField(default='M', max_length=2)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coffeebean')),
            ],
        ),
    ]
