# Generated by Django 4.1.5 on 2023-12-15 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coffee',
            table='coffee',
        ),
        migrations.AlterModelTable(
            name='coffeebean',
            table='coffee_bean',
        ),
    ]
